version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on $(date)

  build:
    commands:
      # Sync files from Source S3 to Client S3 bucket.
      - echo Started syncing files from Source S3 to Client S3 bucket.
      - aws s3 sync --acl public-read s3://$SOURCE_BUCKET_NAME/ s3://$CLIENT_BUCKET_NAME/

  post_build:
    commands:
      # To terminate execution if previous stage fails
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"

      # Invalidation to clear previous cached content
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" s3://$SOURCE_BUCKET_NAME/index.html s3://$CLIENT_BUCKET_NAME/

artifacts:
  files: '**/*'
